// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKyuRkweN3E8OCf8KURsp-qftRiINnSs',
    appId: '1:465577040093:web:fc63baf70bee3be4fd6334',
    messagingSenderId: '465577040093',
    projectId: 'ad-project-mara',
    authDomain: 'ad-project-mara.firebaseapp.com',
    storageBucket: 'ad-project-mara.firebasestorage.app',
    measurementId: 'G-TK0ECY995Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvEJvJGNbpJ05YC1HTuj04yWxmkUrsZNM',
    appId: '1:465577040093:android:7a84e10c26e4cc4bfd6334',
    messagingSenderId: '465577040093',
    projectId: 'ad-project-mara',
    storageBucket: 'ad-project-mara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbfyo0mQ4lTnkdpKHFInA_iRVug2pNZQ',
    appId: '1:465577040093:ios:a4e52d682ef9adaafd6334',
    messagingSenderId: '465577040093',
    projectId: 'ad-project-mara',
    storageBucket: 'ad-project-mara.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutterApp',
  );
}
